{{- if .Values.global.keyvault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default "kv-secrets" .Values.global.keyvault.spClassName }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # for UAMI, keep empty for system-assigned
    keyvaultName: {{ .Values.global.keyvault.name | quote }}
    cloudName: ""
    objects: |
      array:
      {{- range .Values.global.keyvault.objects }}
        - | 
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          objectVersion: "{{ default "" .objectVersion }}"
      {{- end }}
    tenantId: {{ .Values.global.keyvault.tenantId | quote }}
{{- end }}
