apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patient-service.fullname" . }}
  labels:
    app: {{ include "patient-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "patient-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "patient-service.name" . }}
    spec:
      imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 6 }}
      containers:
        - name: patient-service
          image: "{{ default .Values.image.repository .Values.global.registry | printf "%s/%s" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          volumeMounts:
          {{- if .Values.global.keyvault.enabled }}
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.global.keyvault.enabled }}
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ default "kv-secrets" .Values.global.keyvault.spClassName }}
      {{- end }}
